name: Publish to GitHub Packages

on:
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  repository-projects: write


jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: npm ci

      - name: Bump version and publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configura o .npmrc para usar o GitHub Packages
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

          # Obtém a versão publicada no GitHub Packages
          PUBLISHED_VERSION=$(npm show @tooark/eslint version || echo "0.0.0")
          echo "Versão publicada: $PUBLISHED_VERSION"

          # Obtém a versão atual do package.json
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "Versão atual: $CURRENT_VERSION"

          # Compara as versões e incrementa se necessário
          if [ "$CURRENT_VERSION" == "$PUBLISHED_VERSION" ]; then
            echo "Versões são iguais. Incrementando versão..."
            npm version patch -m "Bump version to %s [skip ci]"
          else
            echo "Versões são diferentes. Usando a versão atual."
          fi

          # Configura informações do Git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Faz commit das mudanças de versão
          git add package.json package-lock.json
          git commit -m "Bump version to $(node -p "require('./package.json').version") [skip ci]"

          # Faz push das mudanças e tags
          git push origin HEAD:main --follow-tags

          # Publica o pacote no GitHub Packages
          npm publish --access public
